
export const locationData = [
    { "city": "Mumbai", "country": "India" },
    { "city": "Delhi", "country": "India" },
    { "city": "Bangalore", "country": "India" },
    { "city": "Hyderabad", "country": "India" },
    { "city": "Chennai", "country": "India" },
    { "city": "Kolkata", "country": "India" },
    { "city": "Pune", "country": "India" },
    { "city": "Jaipur", "country": "India" },
    { "city": "Ahmedabad", "country": "India" },
    { "city": "Lucknow", "country": "India" },
    { "city": "Chandigarh", "country": "India" },
    { "city": "Bhopal", "country": "India" },
    { "city": "Indore", "country": "India" },
    { "city": "Nagpur", "country": "India" },
    { "city": "Thiruvananthapuram", "country": "India" },
    { "city": "Kochi", "country": "India" },
    { "city": "Visakhapatnam", "country": "India" },
    { "city": "Patna", "country": "India" },
    { "city": "Guwahati", "country": "India" },
    { "city": "Ranchi", "country": "India" },
    { "city": "Bhubaneswar", "country": "India" },
    { "city": "Agra", "country": "India" },
    { "city": "Varanasi", "country": "India" },
    { "city": "Shimla", "country": "India" },
    { "city": "Darjeeling", "country": "India" },
    { "city": "Goa", "country": "India" },
    { "city": "Tokyo", "country": "Japan" },
    { "city": "New York", "country": "United States" },
    { "city": "Paris", "country": "France" },
    { "city": "London", "country": "United Kingdom" },
    { "city": "Dubai", "country": "United Arab Emirates" },
    { "city": "Singapore", "country": "Singapore" },
    { "city": "Sydney", "country": "Australia" },
    { "city": "Toronto", "country": "Canada" },
    { "city": "Berlin", "country": "Germany" },
    { "city": "Cape Town", "country": "South Africa" },
    { "city": "Moscow", "country": "Russia" },
    { "city": "Bangkok", "country": "Thailand" },
    { "city": "Hong Kong", "country": "Hong Kong" }
];